plugins {
    id 'java-library'
}

group = 'inna_tyulyaeva'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation (
            "org.selenide:selenide-selenoid:2.3.4",
            "com.codeborne:selenide:6.19.1",
            "org.junit.jupiter:junit-jupiter:5.9.3")
}

tasks.withType (JavaCompile) {

    options.encoding = 'UTF-8'

}

test {
    useJUnitPlatform()
}
